# Generated by Django 2.0.7 on 2018-08-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.TextField(unique=True)),
                ('job_type', models.TextField()),
                ('build_type', models.TextField()),
                ('failed_at', models.TextField()),
                ('status', models.TextField()),
                ('reported_by', models.TextField()),
                ('reported_to', models.TextField()),
                ('priority', models.TextField()),
                ('final_comment', models.TextField()),
                ('reason', models.TextField(unique=True)),
            ],
        ),
    ]
