# Generated by Django 2.0.7 on 2018-08-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_updater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpost',
            name='build_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='failed_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='final_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='issue_number',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='job_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='priority',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='reason',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='reported_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='reported_to',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
