# Generated by Django 2.0.7 on 2018-08-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_updater', '0002_auto_20180806_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpost',
            name='last_updated',
            field=models.TextField(default='2018-08-08 18:06:44'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='build_type',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='failed_at',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='final_comment',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='issue_number',
            field=models.TextField(default='N/A', unique=True),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='job_type',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='priority',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='reason',
            field=models.TextField(default='N/A', unique=True),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='reported_by',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='reported_to',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='status',
            field=models.TextField(default='N/A'),
        ),
    ]
