# Generated by Django 2.0.7 on 2018-08-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_updater', '0003_auto_20180808_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpost',
            name='last_updated',
            field=models.TextField(default='2018-08-10 09:52:52'),
        ),
    ]
