# Generated by Django 2.0.7 on 2018-08-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_updater', '0004_auto_20180810_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpost',
            name='responsible_team',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='last_updated',
            field=models.TextField(default='2018-08-10 10:29:51'),
        ),
    ]
