# Generated by Django 2.0.7 on 2018-08-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_updater', '0005_auto_20180810_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpost',
            name='solution',
            field=models.TextField(default='Not Yet Solved'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='last_updated',
            field=models.TextField(default='2018-08-10 10:44:47'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='responsible_team',
            field=models.TextField(default='OTHER'),
        ),
    ]
